AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create the DDB expiry lambda function"
Parameters:
  SgaAnalysisTable:
    Type: String
    Description: The name of the analysis table
  SgaCloudWatchLogsPolicy:
    Type: String
    Description: The ARN for CloudWatchLogs managed policy




  
Resources:


    SgaDdbExpireLambdaRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Ref SgaCloudWatchLogsPolicy
          Policies:
            - PolicyName: DynamoDBPermissions
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:UpdateItem
                    Resource: 
                      - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SgaAnalysisTable}

    SgaSortSGLambda:
      Type: "AWS::Lambda::Function"
      Properties:
        Role: !GetAtt SgaDdbExpireLambdaRole.Arn
        Handler: lambda_function.lambda_handler
        Environment:
          Variables:
            DB_TABLE: !Ref SgaAnalysisTable
            TTL_UPDATE: 30
        Runtime: python3.11
        MemorySize: 256
        Timeout: 900
        Code:
          S3Bucket: !ImportValue sga-resources-bucket-ref
          S3Key: ddb_expire-da30fd83-5206-4dde-b03d-d9606fefc61a.zip