AWSTemplateFormatVersion: 2010-09-09
Description: Enable flow logs

Parameters:
  vpcId:
    Type: String
    Description: vpc id
  logBucketArn:
    Type: String
    Description: ARN for S3 Bucket to output flowlogs

Resources:
  EC2FlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      LogDestinationType: s3
      LogDestination: !Ref logBucketArn
      ResourceId: !Ref vpcId
      ResourceType: VPC
      LogFormat: ${account-id} ${action} ${az_id} ${bytes} ${dstaddr} ${dstport} ${end} ${flow_direction} ${instance_id} ${interface_id} ${log_status} ${packets} ${pkt_dst_aws_service} ${pkt_dstaddr} ${pkt_src_aws_service} ${pkt_srcaddr} ${protocol} ${region} ${srcaddr} ${srcport} ${start} ${sublocation_id} ${sublocation_type} ${subnet_id} ${tcp_flags} ${traffic_path} ${type} ${version} ${vpc_id}