AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create resources for Security Group rules analysis"
Parameters:
  quicksightUserArn:
    Type: String
    Default: ""
Resources:
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "sg-analysis-step-function-role"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"states.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
              - !Sub "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
              - !Sub "arn:aws:iam::aws:policy/AWSXrayFullAccess"

    IAMManagedPolicy:
        Type: "AWS::IAM::ManagedPolicy"
        Properties:
            ManagedPolicyName: "SG_Analysis_Amazon_EventBridge_Invoke_Step_Functions"
            Path: "/service-role/"
            PolicyDocument: !Sub |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "states:StartExecution"
                            ],
                            "Resource": [
                                "${StepFunctionsStateMachine}"
                            ]
                        }
                    ]
                }

    IAMRole2:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "SG_Analysis_Glue_Access_Role"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"glue.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
              - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
              - "arn:aws:iam::aws:policy/AmazonSESFullAccess"
              - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
              - "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
              - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
              - "arn:aws:iam::aws:policy/AmazonS3FullAccess"

    StepFuncLogGroup:
        Type: "AWS::Logs::LogGroup"
        Properties:
            LogGroupName: "/aws/vendedlogs/states/sg-analysis-step-function-logs"

    DynamoTableSGRules:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: sg-analysis-rules-data
          AttributeDefinitions:
            - AttributeName: sg_rule_id
              AttributeType: S
            - AttributeName: security_group_id
              AttributeType: S
          KeySchema:
            - AttributeName: sg_rule_id
              KeyType: HASH
            - AttributeName: security_group_id
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

    DynamoTableSGAnalysis:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: sg-analysis-rules-usage
          GlobalSecondaryIndexes:
            - IndexName: protocol
              KeySchema:
              - AttributeName: sg_id
                KeyType: HASH 
              - AttributeName: protocol
                KeyType: RANGE
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
          AttributeDefinitions:
            - AttributeName: sg_rule_id
              AttributeType: S
            - AttributeName: sg_id
              AttributeType: S
            - AttributeName: protocol
              AttributeType: S
          KeySchema:
            - AttributeName: sg_rule_id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

    S3BucketAthena:
      Type: "AWS::S3::Bucket"
      DeletionPolicy: Retain
      Properties:
        BucketName: security-group-monitoring-test-bucket-athena

    S3BucketFlowlogs:
      Type: "AWS::S3::Bucket"
      DeletionPolicy: Retain
      Properties:
        BucketName: security-group-monitoring-test-bucket-flowlogs

    S3BucketResources:
      Type: "AWS::S3::Bucket"
      DeletionPolicy: Retain
      Properties:
        BucketName: security-group-monitoring-test-bucket-resources


    StepFunctionsStateMachine:
        Type: "AWS::StepFunctions::StateMachine"
        Properties:
            StateMachineName: !Ref EventsRule
            DefinitionString: |
                {
                  "Comment": "A description of my state machine",
                  "StartAt": "Glue GetSGRulesData",
                  "States": {
                    "Glue GetSGRulesData": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Parameters": {
                        "JobName": "sg-analysis-get-rules-data"
                      },
                      "Next": "Glue QueryVPCFlowLogsSaveToS3"
                    },
                    "Glue QueryVPCFlowLogsSaveToS3": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Parameters": {
                        "JobName": "sg-analysis-run-athena-query"
                      },
                      "Next": "Glue ParseVPCFLowLogsSaveUsageCount"
                    },
                    "Glue ParseVPCFLowLogsSaveUsageCount": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Parameters": {
                        "JobName": "sg-analysis-flow-logs-parser"
                      },
                      "End": true
                    }
                  }
                }
            RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/sg-analysis-step-function-role"
            StateMachineType: "STANDARD"
            LoggingConfiguration:
                Destinations: 
                  - CloudWatchLogsLogGroup: 
                        LogGroupArn: !GetAtt StepFuncLogGroup.Arn
                IncludeExecutionData: true
                Level: "ALL"
            
    EventsRule:
        Type: "AWS::Events::Rule"
        Properties:
            Name: "sg-analysis-step-function"
            ScheduleExpression: "cron(0 9 * * ? *)"
            State: "DISABLED"
            Targets: 
              - 
                Arn: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sg-analysis-step-function"
                Id: "Id70bcbcb6-9bda-4f24-8f45-8f3dbb65692c"
                RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/SG_Analysis_Amazon_EventBridge_Invoke_Step_Functions"
            EventBusName: "default"

    GlueJob1:
        Type: "AWS::Glue::Job"
        Properties:
            Name: "sg-analysis-run-athena-query"
            Description: "Job to run Athena query on VPC Flow logs and save to S3"
            Role: !GetAtt IAMRole2.Arn
            ExecutionProperty: 
                MaxConcurrentRuns: 1
            Command: 
                Name: "pythonshell"
                ScriptLocation: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/scripts/'
                                      - 'query_athena.py'
                PythonVersion: "3.9"
            DefaultArguments: 
                --TempDir: !Join
                                - ''
                                - - 's3://'
                                  - !Ref S3BucketResources
                                  - '/temporary/'
                --class: "GlueApp"
                --enable-glue-datacatalog: "true"
                --enable-job-insights: "false"
                --job-language: "python"
                --prebuilt-library-option: "prebuilt-library-enable"
            MaxRetries: 1
            Timeout: 2880
            GlueVersion: "1.0"
            MaxCapacity: 0.0625

    GlueJob2:
        Type: "AWS::Glue::Job"
        Properties:
            Name: "sg-analysis-get-rules-data"
            Description: "Job to get Security Group rules information"
            Role: !GetAtt IAMRole2.Arn
            ExecutionProperty: 
                MaxConcurrentRuns: 1
            Command: 
                Name: "pythonshell"
                ScriptLocation: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/scripts/'
                                      - 'get_security_groups_data.py'
                PythonVersion: "3.9"
            DefaultArguments: 
                --class: "GlueApp"
                --enable-job-insights: "false"
                --extra-py-files: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/libraries/'
                                      - 'boto3-1.27.1-py3-none-any.whl'
                --job-language: "python"
            MaxRetries: 1
            Timeout: 2880
            GlueVersion: "1.0"
            MaxCapacity: 0.0625

    GlueJob3:
        Type: "AWS::Glue::Job"
        Properties:
            Name: "sg-analysis-flow-logs-parser"
            Description: "Job to parse flow logs and calculate usage"
            Role: !GetAtt IAMRole2.Arn
            ExecutionProperty: 
                MaxConcurrentRuns: 1
            Command: 
                Name: "pythonshell"
                ScriptLocation: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/scripts/'
                                      - 'flow_logs_parser.py'
                PythonVersion: "3.9"
            DefaultArguments: 
                --class: "GlueApp"
                --enable-job-insights: "false"
                --extra-py-files: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/libraries/'
                                      - 'awswrangler-2.14.0-py3-none-any.whl'
                --job-language: "python"
            MaxRetries: 1
            Timeout: 2880
            GlueVersion: "1.0"
            MaxCapacity: 1