AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create resources for Security Group rules analysis"
Parameters:
  quicksightUserArn:
    Type: String
    Default: ""
Resources:

    SgaCloudWatchLogsPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
          Description: Managed policy for CloudWatch Logs for use with the Security Group Analysis Solution
          Path: "/"
    
    SgaStepFunctionIAMRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service: states.amazonaws.com
                Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
            - !Ref SgaCloudWatchLogsPolicy
          Policies:
            - PolicyName: SgaSfLambdaInvokePolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - lambda:InvokeFunction
                    Resource:
                      - !GetAtt LambdaGetSG.Arn
                      - !GetAtt LambdaGetENI.Arn
            - PolicyName: SgaSfCwlStepFunctions
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogDelivery
                      - logs:GetLogDelivery
                      - logs:UpdateLogDelivery
                      - logs:DeleteLogDelivery
                      - logs:ListLogDeliveries
                      - logs:PutResourcePolicy
                      - logs:DescribeResourcePolicies
                      - logs:DescribeLogGroups
                    Resource: "*"

    IAMManagedPolicy:
        Type: "AWS::IAM::ManagedPolicy"
        Properties:
            ManagedPolicyName: "SG_Analysis_Amazon_EventBridge_Invoke_Step_Functions_KS"
            Path: "/service-role/"
            PolicyDocument: !Sub |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "states:StartExecution"
                            ],
                            "Resource": [
                                "${StepFunctionsStateMachine}"
                            ]
                        }
                    ]
                }

    StepFuncLogGroup:
        Type: "AWS::Logs::LogGroup"
        Properties:
            LogGroupName: "/aws/vendedlogs/states/sg-analysis-step-function-logs_KS"

    DynamoTableSGRules:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: sg-analysis-rules-data-ks
          GlobalSecondaryIndexes:
            - IndexName: groups
              KeySchema:
              - AttributeName: group_id
                KeyType: HASH 
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
            - AttributeName: group_id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

    DynamoTableSGAnalysis:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: sg-analysis-rules-usage-ks
          GlobalSecondaryIndexes:
            - IndexName: protocol
              KeySchema:
              - AttributeName: sg_id
                KeyType: HASH 
              - AttributeName: protocol
                KeyType: RANGE
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
          AttributeDefinitions:
            - AttributeName: sgr_flow_hash
              AttributeType: S
            - AttributeName: sg_id
              AttributeType: S
            - AttributeName: protocol
              AttributeType: S
          KeySchema:
            - AttributeName: sgr_flow_hash
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      
    DynamoTablENIAnalysis:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: sg-analysis-interface-details-ks
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

    S3BucketAthena:
      Type: "AWS::S3::Bucket"
      # DeletionPolicy: Retain
      Properties:
        BucketName: security-group-monitoring-test-bucket-athena-ks

    S3BucketFlowlogs:
      Type: "AWS::S3::Bucket"
      # DeletionPolicy: Retain
      Properties:
        BucketName: security-group-monitoring-test-bucket-flowlogs-ks

    S3BucketResources:
      Type: "AWS::S3::Bucket"
      # DeletionPolicy: Retain
      Properties:
        BucketName: security-group-monitoring-test-bucket-resources-ks


    StepFunctionsStateMachine:
        Type: "AWS::StepFunctions::StateMachine"
        Properties:
            StateMachineName: !Ref EventsRule
            DefinitionString: |
                {
                  "Comment": "A description of my state machine",
                  "StartAt": "Glue GetSGRulesData",
                  "States": {
                    "Glue GetSGRulesData": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Parameters": {
                        "JobName": "sg-analysis-get-rules-data-ks"
                      },
                      "Next": "Glue QueryVPCFlowLogsSaveToS3"
                    },
                    "Glue QueryVPCFlowLogsSaveToS3": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Parameters": {
                        "JobName": "sg-analysis-run-athena-query-ks"
                      },
                      "Next": "Glue ParseVPCFLowLogsSaveUsageCount"
                    },
                    "Glue ParseVPCFLowLogsSaveUsageCount": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Parameters": {
                        "JobName": "sg-analysis-flow-logs-parser-ks"
                      },
                      "End": true
                    }
                  }
                }
            RoleArn: !GetAtt SgaStepFunctionIAMRole.Arn
            StateMachineType: "STANDARD"
            LoggingConfiguration:
                Destinations: 
                  - CloudWatchLogsLogGroup: 
                        LogGroupArn: !GetAtt StepFuncLogGroup.Arn
                IncludeExecutionData: true
                Level: "ALL"
            
    EventsRule:
        Type: "AWS::Events::Rule"
        Properties:
            Name: "sg-analysis-step-function-ks"
            ScheduleExpression: "cron(0 9 * * ? *)"
            State: "DISABLED"
            Targets: 
              - 
                Arn: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sg-analysis-step-function"
                Id: "Id70bcbcb6-9bda-4f24-8f45-8f3dbb65692c"
                RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/SG_Analysis_Amazon_EventBridge_Invoke_Step_Functions"
            EventBusName: "default"

    SgaStartAthenaQueryGlueJobIAMRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service: glue.amazonaws.com
                Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Ref SgaCloudWatchLogsPolicy
          Policies:
            - PolicyName: GlueJobPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - athena:StartQueryExecution
                      - athena:GetQueryExecution
                      - athena:GetQueryResults
                    Resource: "*"
            - PolicyName: GlueJobS3Access
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - s3:Get*
                      - s3:HeadObject
                      - s3:List*
                    Resource:
                      - arn:aws:s3:::security-group-monitoring-test-res-bucket
                      - arn:aws:s3:::security-group-monitoring-test-res-bucket/*
                      - arn:aws:s3:::security-group-monitoring-test-bucket-athena
                      - arn:aws:s3:::security-group-monitoring-test-bucket-athena/*

    GlueJob1:
        Type: "AWS::Glue::Job"
        Properties:
            Name: "sg-analysis-run-athena-query-ks"
            Description: "Job to run Athena query on VPC Flow logs and save to S3"
            Role: !GetAtt SgaStartAthenaQueryGlueJobIAMRole.Arn
            ExecutionProperty: 
                MaxConcurrentRuns: 1
            Command: 
                Name: "pythonshell"
                ScriptLocation: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/scripts/'
                                      - 'query_athena.py'
                PythonVersion: "3.9"
            DefaultArguments: 
                --TempDir: !Join
                                - ''
                                - - 's3://'
                                  - !Ref S3BucketResources
                                  - '/temporary/'
                --class: "GlueApp"
                --enable-glue-datacatalog: "true"
                --enable-job-insights: "false"
                --job-language: "python"
                --prebuilt-library-option: "prebuilt-library-enable"
            MaxRetries: 1
            Timeout: 2880
            GlueVersion: "1.0"
            MaxCapacity: 0.0625

    SgaParseFlowLogsGlueJobIAMRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service: glue.amazonaws.com
                Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Ref SgaCloudWatchLogsPolicy
          Policies:
              - PolicyName: GlueJobS3Access
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - s3:Get*
                          - s3:HeadObject
                          - s3:List*
                        Resource:
                          - arn:aws:s3:::security-group-monitoring-test-res-bucket
                          - arn:aws:s3:::security-group-monitoring-test-res-bucket/*
                          - arn:aws:s3:::security-group-monitoring-test-bucket-athena
                          - arn:aws:s3:::security-group-monitoring-test-bucket-athena/*
              - PolicyName: GlueJobDynamoDBPolicy
                PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - dynamodb:Query
                        - dynamodb:GetItem
                      Resource:
                        - !GetAtt DynamoTableSGRules.Arn
                        - !GetAtt DynamoTablENIAnalysis.Arn
              - PolicyName: GlueJobDynamoDBReadWritePolicy
                PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - dynamodb:PutItem
                        - dynamodb:GetItem
                        - dynamodb:UpdateItem
                      Resource: !GetAtt DynamoTableSGAnalysis.Arn
    
    GlueJob3:
        Type: "AWS::Glue::Job"
        Properties:
            Name: "sg-analysis-flow-logs-parser-ks"
            Description: "Job to parse flow logs and calculate usage"
            Role: !GetAtt SgaParseFlowLogsGlueJobIAMRole.Arn
            ExecutionProperty: 
                MaxConcurrentRuns: 1
            Command: 
                Name: "pythonshell"
                ScriptLocation: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/scripts/'
                                      - 'flow_logs_parser.py'
                PythonVersion: "3.9"
            DefaultArguments: 
                --class: "GlueApp"
                --enable-job-insights: "false"
                --extra-py-files: !Join
                                    - ''
                                    - - 's3://'
                                      - !Ref S3BucketResources
                                      - '/libraries/'
                                      - 'awswrangler-2.14.0-py3-none-any.whl'
                --job-language: "python"
            MaxRetries: 1
            Timeout: 2880
            GlueVersion: "1.0"
            MaxCapacity: 1

    SgaGetSgLambdaIAMRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Ref SgaCloudWatchLogsPolicy
          Policies:
            - PolicyName: DescribeSecurityGroupsPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - ec2:DescribeSecurityGroups
                      - ec2:DescribeSecurityGroupReferences
                      - ec2:DescribeSecurityGroupRules
                    Resource: "*"
            - PolicyName: DynamoDBPermissions
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:PutItem
                      - dynamodb:Query
                    Resource: !GetAtt DynamoTableSGRules.Arn

    LambdaGetSG:
      Type: "AWS::Lambda::Function"
      Properties:
        Role: !GetAtt SgaGetSgLambdaIAMRole.Arn
        Handler: lambda_function.lambda_handler
        Environment:
          Variables:
            DB_TABLE: !Ref DynamoTableSGRules
        Runtime: python3.10
        Code:
          S3Bucket: security-group-monitoring-test-bucket-resources
          S3Key: GetSGTest-5635c8ba-9036-4b27-a232-ffb9f8874040.zip

    SgaGetEniLambdaIAMRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Path: /
          ManagedPolicyArns:
            - !Ref SgaCloudWatchLogsPolicy
          Policies:
            - PolicyName: DescribeSecurityGroupsPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - ec2:DescribeNetworkInterfaces
                      - ec2:DescribeTags
                      - ec2:DescribeNetworkAcls
                      - ec2:DescribeRouteTables
                    Resource: "*"
            - PolicyName: DynamoDBPermissions
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:PutItem
                      - dynamodb:Query
                    Resource: !GetAtt DynamoTablENIAnalysis.Arn

    LambdaGetENI:
      Type: "AWS::Lambda::Function"
      Properties:
        Role: !GetAtt SgaGetEniLambdaIAMRole.Arn
        Handler: lambda_function.lambda_handler
        Environment:
          Variables:
            DB_TABLE: !GetAtt DynamoTablENIAnalysis.Arn
        Runtime: python3.10
        Code:
          S3Bucket: security-group-monitoring-test-bucket-resources
          S3Key: GetENITest-787e5a66-3dc8-4c70-b8a6-f9e4ba4761d5.zip
